/**
 * ÉTAT INITIAL - PROFESSIONALS & PARTNERS
 * Données d'annuaire pour tous les professionnels et partenaires
 */

import type { Professional } from '../types/business.types';

// ============================================================
// PROFESSIONALS (Annuaire principal)
// ============================================================

export const initialProfessionals: Professional[] = [
  {
    id: 'pro-1',
    name: 'Marc Dubois',
    role: 'artisan',
    specialty: 'Plombier spécialisé restaurants',
    location: 'Paris 11e',
    rating: 4.8,
    reviewCount: 127,
    price: '65€/h',
    availability: 'Disponible maintenant',
    verified: true,
    avatar: 'https://ui-avatars.com/api/?name=Marc+Dubois&background=3b82f6&color=fff&size=100',
    badges: ['Urgence 2h', 'Pro vérifié', 'Spécialiste resto'],
    description: '15 ans d\'expérience dans la plomberie pour restaurants. Spécialisé en urgence et maintenance préventive.',
    ecoFriendly: true,
    skills: ['Plomberie', 'Sanitaire', 'Urgence', 'Maintenance'],
    experience: '15 ans',
    portfolio: []
  },
  {
    id: 'pro-2',
    name: 'Sophie Martin',
    role: 'community_manager',
    specialty: 'Expert Instagram restaurants',
    location: 'Lyon',
    rating: 4.9,
    reviewCount: 89,
    price: '450€/mois',
    availability: '2 créneaux libres',
    verified: true,
    avatar: 'https://ui-avatars.com/api/?name=Sophie+Martin&background=10b981&color=fff&size=100',
    badges: ['Top CM', 'Food expert', 'Instagram +50K'],
    description: 'Community Manager spécialisée food. +50 restaurants accompagnés. Création de contenu et stratégie digitale.',
    ecoFriendly: false,
    skills: ['Instagram', 'Facebook', 'TikTok', 'Photographie culinaire'],
    experience: '5 ans',
    portfolio: []
  },
  {
    id: 'pro-3',
    name: 'Thomas Leclerc',
    role: 'candidat',
    specialty: 'Chef de partie expérimenté',
    location: 'Paris',
    rating: 4.6,
    reviewCount: 45,
    price: '2400€/mois',
    availability: 'Disponible immédiatement',
    verified: true,
    avatar: 'https://ui-avatars.com/api/?name=Thomas+Leclerc&background=8b5cf6&color=fff&size=100',
    badges: ['CDI recherché', '8 ans exp', 'Gastronomie'],
    description: 'Chef de partie avec 8 ans d\'expérience en cuisine gastronomique. Recherche poste stable en CDI.',
    ecoFriendly: false,
    skills: ['Cuisine française', 'Gestion équipe', 'Menu création', 'Hygiène HACCP'],
    experience: '8 ans',
    portfolio: []
  },
  {
    id: 'pro-4',
    name: 'BioFresh Distribution',
    role: 'fournisseur',
    specialty: 'Légumes bio locaux',
    location: 'Île-de-France',
    rating: 4.7,
    reviewCount: 203,
    price: 'Sur devis',
    availability: 'Stock disponible',
    verified: true,
    avatar: 'https://ui-avatars.com/api/?name=BioFresh+Distribution&background=059669&color=fff&size=100',
    badges: ['Bio certifié', 'Livraison 24h', 'Local +100km'],
    description: 'Fournisseur de légumes bio locaux. Producteurs partenaires dans un rayon de 100km. Livraison quotidienne.',
    ecoFriendly: true,
    skills: ['Agriculture bio', 'Logistique', 'Traçabilité', 'Conseil nutri'],
    experience: '12 ans',
    portfolio: []
  },
  {
    id: 'pro-banquier-1',
    name: 'Jean-Pierre Crédit',
    role: 'banquier',
    specialty: 'Financement restaurant et commerce',
    location: 'Paris La Défense',
    rating: 4.7,
    reviewCount: 95,
    price: 'Gratuit (commissions)',
    availability: 'Disponible sur RDV',
    verified: true,
    avatar: 'https://ui-avatars.com/api/?name=Jean-Pierre+Credit&background=1e40af&color=fff&size=100',
    badges: ['Banque partenaire', 'Expert resto', 'Taux préférentiels'],
    description: 'Conseiller bancaire spécialisé dans le financement de restaurants. 12 ans d\'expérience, taux négociés.',
    ecoFriendly: false,
    skills: ['Prêts professionnels', 'Assurances', 'Trésorerie', 'Conseil financier'],
    experience: '12 ans',
    portfolio: []
  },
  {
    id: 'pro-investisseur-1',
    name: 'Marie Venture Capital',
    role: 'investisseur',
    specialty: 'Investissement restaurants innovants',
    location: 'Neuilly-sur-Seine',
    rating: 4.9,
    reviewCount: 34,
    price: '50K-500K€',
    availability: 'Sélectif',
    verified: true,
    avatar: 'https://ui-avatars.com/api/?name=Marie+Venture&background=7c3aed&color=fff&size=100',
    badges: ['Business Angel', 'Food Tech', 'Accompagnement'],
    description: 'Investisseuse spécialisée Food Tech. Portfolio de 15 restaurants. Accompagnement stratégique inclus.',
    ecoFriendly: true,
    skills: ['Due diligence', 'Stratégie', 'Levée de fonds', 'Mentoring'],
    experience: '8 ans',
    portfolio: []
  },
  {
    id: 'pro-comptable-1',
    name: 'François Expert-Comptable',
    role: 'comptable',
    specialty: 'Comptabilité restaurants et CHR',
    location: 'Paris 9e',
    rating: 4.8,
    reviewCount: 156,
    price: '180€/mois',
    availability: 'Nouveaux clients acceptés',
    verified: true,
    avatar: 'https://ui-avatars.com/api/?name=Francois+Expert&background=dc2626&color=fff&size=100',
    badges: ['Expert-comptable', 'Spécialiste CHR', 'Déclarations'],
    description: 'Expert-comptable spécialisé CHR. Gestion complète, optimisation fiscale, conseils de gestion.',
    ecoFriendly: false,
    skills: ['Comptabilité', 'Fiscal', 'Social', 'Gestion', 'TVA'],
    experience: '15 ans',
    portfolio: []
  },
  {
    id: 'pro-restaurant-1',
    name: 'Le Gourmet Parisien',
    role: 'restaurant',
    specialty: 'Cuisine française traditionnelle',
    location: 'Paris 5e',
    rating: 4.6,
    reviewCount: 284,
    price: '35-55€',
    availability: 'Ouvert',
    verified: true,
    avatar: 'https://ui-avatars.com/api/?name=Le+Gourmet&background=f59e0b&color=fff&size=100',
    badges: ['Maître Restaurateur', 'Terrasse', 'Groupes'],
    description: 'Restaurant traditionnel français. Cuisine maison avec produits de saison. Terrasse 40 places.',
    ecoFriendly: true,
    skills: ['Cuisine française', 'Produits locaux', 'Service', 'Événements'],
    experience: '20 ans',
    portfolio: []
  }
];

// ============================================================
// PARTNERS (Annuaire par catégorie - Plus détaillé)
// ============================================================

export const initialPartners: Professional[] = [
  // ========== RESTAURANTS ==========
  {
    id: 'partner-restaurant-1',
    name: 'Le Bistrot Gourmand',
    role: 'restaurant',
    specialty: 'Cuisine française traditionnelle',
    location: 'Paris 11e',
    rating: 4.7,
    reviewCount: 342,
    price: '30-50€',
    availability: 'Ouvert',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=11',
    badges: ['Maître Restaurateur', 'Terrasse', 'Bio'],
    description: 'Restaurant familial depuis 1985. Cuisine française traditionnelle avec produits locaux.',
    ecoFriendly: true,
    skills: ['Cuisine française', 'Produits locaux', 'Service traiteur'],
    experience: '38 ans'
  },
  {
    id: 'partner-restaurant-2',
    name: 'La Table du Chef',
    role: 'restaurant',
    specialty: 'Cuisine gastronomique',
    location: 'Lyon 2e',
    rating: 4.9,
    reviewCount: 567,
    price: '70-120€',
    availability: 'Réservation requise',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=12',
    badges: ['1 Étoile Michelin', 'Chef reconnu', 'Cave premium'],
    description: 'Restaurant gastronomique étoilé. Menu dégustation créatif avec accords mets-vins.',
    ecoFriendly: true,
    skills: ['Haute gastronomie', 'Accords mets-vins', 'Menu dégustation'],
    experience: '15 ans'
  },
  {
    id: 'partner-restaurant-3',
    name: 'Sushi Master',
    role: 'restaurant',
    specialty: 'Cuisine japonaise authentique',
    location: 'Marseille 6e',
    rating: 4.6,
    reviewCount: 289,
    price: '40-80€',
    availability: 'Ouvert',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=13',
    badges: ['Chef japonais', 'Poissons frais', 'Spécialités sashimi'],
    description: 'Sushi bar authentique tenu par un chef japonais. Poisson ultra-frais livré quotidiennement.',
    ecoFriendly: false,
    skills: ['Sushi', 'Sashimi', 'Tempura', 'Cuisine japonaise'],
    experience: '22 ans'
  },
  {
    id: 'partner-restaurant-4',
    name: 'Pizza Bella Napoli',
    role: 'restaurant',
    specialty: 'Pizzeria napolitaine',
    location: 'Nice 1er',
    rating: 4.5,
    reviewCount: 412,
    price: '12-25€',
    availability: 'Ouvert',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=14',
    badges: ['Four à bois', 'Recette napolitaine', 'Livraison'],
    description: 'Pizzeria traditionnelle napolitaine. Four à bois, pâte maison, produits italiens importés.',
    ecoFriendly: true,
    skills: ['Pizza napolitaine', 'Pasta maison', 'Antipasti'],
    experience: '12 ans'
  },
  {
    id: 'partner-restaurant-5',
    name: 'Le Végétal',
    role: 'restaurant',
    specialty: 'Cuisine végétarienne & vegan',
    location: 'Bordeaux 1er',
    rating: 4.8,
    reviewCount: 234,
    price: '18-35€',
    availability: 'Ouvert',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=15',
    badges: ['100% végétal', 'Bio', 'Sans gluten'],
    description: 'Restaurant végétarien et vegan. Cuisine créative avec produits bio et locaux.',
    ecoFriendly: true,
    skills: ['Cuisine vegan', 'Sans gluten', 'Bio', 'Local'],
    experience: '6 ans'
  },

  // ========== FOURNISSEURS ==========
  {
    id: 'partner-fournisseur-1',
    name: 'BioFresh Distribution',
    role: 'fournisseur',
    specialty: 'Fruits et légumes bio',
    location: 'Rungis',
    rating: 4.7,
    reviewCount: 178,
    price: 'Sur devis',
    availability: 'Livraison quotidienne',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=21',
    badges: ['Certification AB', 'Livraison rapide', 'Producteurs locaux'],
    description: 'Grossiste en fruits et légumes bio. Approvisionnement direct producteurs. Livraison 6j/7.',
    ecoFriendly: true,
    skills: ['Fruits bio', 'Légumes bio', 'Logistique', 'Fraîcheur'],
    experience: '18 ans'
  },
  {
    id: 'partner-fournisseur-2',
    name: 'Viandes Premium',
    role: 'fournisseur',
    specialty: 'Viandes de qualité supérieure',
    location: 'Lyon',
    rating: 4.9,
    reviewCount: 245,
    price: 'Sur devis',
    availability: 'Commande 48h',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=22',
    badges: ['Label Rouge', 'Race à viande', 'Traçabilité'],
    description: 'Fournisseur de viandes haut de gamme. Bœuf, agneau, volaille Label Rouge. Découpe sur mesure.',
    ecoFriendly: false,
    skills: ['Boucherie', 'Découpe', 'Maturation', 'Conseils'],
    experience: '25 ans'
  },
  {
    id: 'partner-fournisseur-3',
    name: 'Poissonnerie de la Criée',
    role: 'fournisseur',
    specialty: 'Poissons et fruits de mer',
    location: 'Marseille',
    rating: 4.8,
    reviewCount: 198,
    price: 'Tarif marché',
    availability: 'Livraison quotidienne',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=23',
    badges: ['Pêche locale', 'Ultra-frais', 'Traçabilité MSC'],
    description: 'Poissonnerie en direct de la criée. Poissons et fruits de mer ultra-frais, pêche locale.',
    ecoFriendly: true,
    skills: ['Poissons frais', 'Fruits de mer', 'Écaillage', 'Filetage'],
    experience: '32 ans'
  },
  {
    id: 'partner-fournisseur-4',
    name: 'Vins & Spiritueux Prestige',
    role: 'fournisseur',
    specialty: 'Vins et spiritueux',
    location: 'Bordeaux',
    rating: 4.9,
    reviewCount: 312,
    price: 'Sur devis',
    availability: 'Stock permanent',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=24',
    badges: ['Grands crus', 'Sommelier conseil', 'Livraison France'],
    description: 'Négociant en vins et spiritueux. Grands crus, vins régionaux, conseils personnalisés.',
    ecoFriendly: false,
    skills: ['Vins', 'Spiritueux', 'Conseil', 'Accords mets-vins'],
    experience: '28 ans'
  },
  {
    id: 'partner-fournisseur-5',
    name: 'Épicerie Fine du Monde',
    role: 'fournisseur',
    specialty: 'Produits d\'épicerie fine',
    location: 'Paris 3e',
    rating: 4.6,
    reviewCount: 156,
    price: 'Sur devis',
    availability: 'Commande 24h',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=25',
    badges: ['Produits rares', 'Import direct', 'Épices du monde'],
    description: 'Importateur de produits d\'épicerie fine. Épices, huiles, condiments du monde entier.',
    ecoFriendly: true,
    skills: ['Épices', 'Huiles', 'Condiments', 'Produits exotiques'],
    experience: '14 ans'
  },

  // ========== ARTISANS ==========
  {
    id: 'partner-artisan-1',
    name: 'Jean-Marc Plomberie',
    role: 'artisan',
    specialty: 'Plomberie professionnelle',
    location: 'Paris',
    rating: 4.8,
    reviewCount: 234,
    price: '65€/h',
    availability: 'Urgence 24/7',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=31',
    badges: ['Urgence 2h', 'Spécialiste CHR', 'Devis gratuit'],
    description: 'Plombier spécialisé restaurants. Installation, dépannage, maintenance. Intervention rapide.',
    ecoFriendly: true,
    skills: ['Plomberie', 'Sanitaire', 'Chauffage', 'Urgence'],
    experience: '19 ans'
  },
  {
    id: 'partner-artisan-2',
    name: 'Électricité Pro Services',
    role: 'artisan',
    specialty: 'Installation électrique CHR',
    location: 'Lyon',
    rating: 4.7,
    reviewCount: 189,
    price: '60€/h',
    availability: 'Du lundi au samedi',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=32',
    badges: ['Certifié Qualifelec', 'Conformité normes', 'Dépannage'],
    description: 'Électricien spécialisé CHR. Installation cuisine pro, mise aux normes, dépannage.',
    ecoFriendly: false,
    skills: ['Électricité', 'Tableaux électriques', 'Éclairage', 'Maintenance'],
    experience: '22 ans'
  },
  {
    id: 'partner-artisan-3',
    name: 'Froid Expertise',
    role: 'artisan',
    specialty: 'Froid commercial et climatisation',
    location: 'Marseille',
    rating: 4.9,
    reviewCount: 276,
    price: '70€/h',
    availability: 'Intervention rapide',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=33',
    badges: ['Spécialiste froid', 'Contrat maintenance', 'Urgence'],
    description: 'Expert en froid commercial. Installation, réparation, maintenance chambres froides et vitrines.',
    ecoFriendly: true,
    skills: ['Chambres froides', 'Climatisation', 'Maintenance', 'Fluides frigorigènes'],
    experience: '16 ans'
  },
  {
    id: 'partner-artisan-4',
    name: 'Menuiserie Restaurant',
    role: 'artisan',
    specialty: 'Aménagement sur mesure',
    location: 'Toulouse',
    rating: 4.6,
    reviewCount: 143,
    price: 'Sur devis',
    availability: 'Rendez-vous sur demande',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=34',
    badges: ['Sur mesure', 'Bois noble', 'Design'],
    description: 'Menuisier ébéniste. Aménagement restaurant sur mesure, mobilier, bar, terrasse.',
    ecoFriendly: true,
    skills: ['Menuiserie', 'Ébénisterie', 'Design', 'Aménagement'],
    experience: '24 ans'
  },
  {
    id: 'partner-artisan-5',
    name: 'Peinture & Décoration Pro',
    role: 'artisan',
    specialty: 'Peinture et décoration',
    location: 'Nice',
    rating: 4.5,
    reviewCount: 167,
    price: '45€/h',
    availability: 'Disponible',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=35',
    badges: ['Travail soigné', 'Délais respectés', 'Conseils déco'],
    description: 'Peintre décorateur professionnel. Peinture, papier peint, enduits décoratifs.',
    ecoFriendly: true,
    skills: ['Peinture', 'Décoration', 'Enduits', 'Couleurs'],
    experience: '13 ans'
  },

  // ========== TRANSPORTEURS ==========
  {
    id: 'partner-transporteur-1',
    name: 'Express Livraison Pro',
    role: 'transporteur',
    specialty: 'Livraison express restauration',
    location: 'Paris & Région',
    rating: 4.7,
    reviewCount: 412,
    price: 'À partir de 15€',
    availability: '7j/7, 6h-23h',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=41',
    badges: ['Véhicules frigo', 'Livraison express', 'Suivi temps réel'],
    description: 'Service de livraison spécialisé restauration. Véhicules frigorifiques, livraison express.',
    ecoFriendly: true,
    skills: ['Livraison rapide', 'Chaîne du froid', 'Traçabilité', 'Ponctualité'],
    experience: '11 ans'
  },
  {
    id: 'partner-transporteur-2',
    name: 'Logistique Food Service',
    role: 'transporteur',
    specialty: 'Transport alimentaire',
    location: 'Nationale',
    rating: 4.8,
    reviewCount: 523,
    price: 'Sur devis',
    availability: 'Planning flexible',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=42',
    badges: ['Flotte nationale', 'Température contrôlée', 'Certifié HACCP'],
    description: 'Transporteur alimentaire national. Respect chaîne du froid, traçabilité complète.',
    ecoFriendly: false,
    skills: ['Transport frigo', 'Logistique', 'HACCP', 'National'],
    experience: '23 ans'
  },
  {
    id: 'partner-transporteur-3',
    name: 'Coursiers Écologiques',
    role: 'transporteur',
    specialty: 'Livraison vélo & électrique',
    location: 'Grandes villes',
    rating: 4.6,
    reviewCount: 298,
    price: '8-20€',
    availability: 'Lun-Sam 7h-22h',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=43',
    badges: ['100% écolo', 'Vélo cargo', 'Rapide en ville'],
    description: 'Coursiers écologiques à vélo et véhicules électriques. Livraison rapide en centre-ville.',
    ecoFriendly: true,
    skills: ['Livraison écolo', 'Vélo cargo', 'Rapidité', 'Centre-ville'],
    experience: '5 ans'
  },

  // ========== COMMUNITY MANAGERS ==========
  {
    id: 'partner-cm-1',
    name: 'Digital Food Expert',
    role: 'community_manager',
    specialty: 'Social media restaurants',
    location: 'Remote / Paris',
    rating: 4.9,
    reviewCount: 167,
    price: '550€/mois',
    availability: '3 créneaux libres',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=51',
    badges: ['Food expert', 'Instagram +100K', 'Campagnes pub'],
    description: 'Community Manager spécialisé restauration. Stratégie social media, création contenu, publicités.',
    ecoFriendly: false,
    skills: ['Instagram', 'Facebook', 'TikTok', 'Publicités', 'Stratégie digitale'],
    experience: '7 ans'
  },
  {
    id: 'partner-cm-2',
    name: 'Content Creator Food',
    role: 'community_manager',
    specialty: 'Photo & vidéo culinaire',
    location: 'Lyon',
    rating: 4.8,
    reviewCount: 234,
    price: '450€/mois',
    availability: 'Disponible',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=52',
    badges: ['Photographe pro', 'Vidéo', 'TikTok viral'],
    description: 'Créateur de contenu culinaire. Photo pro, vidéo, reels Instagram/TikTok. Portfolio +50 restos.',
    ecoFriendly: false,
    skills: ['Photographie culinaire', 'Vidéo', 'Montage', 'Reels'],
    experience: '5 ans'
  },
  {
    id: 'partner-cm-3',
    name: 'Social Media Manager Pro',
    role: 'community_manager',
    specialty: 'Gestion complète réseaux sociaux',
    location: 'Remote',
    rating: 4.7,
    reviewCount: 189,
    price: '650€/mois',
    availability: '2 créneaux',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=53',
    badges: ['Multi-plateformes', 'Campagnes ROI', 'Analytics'],
    description: 'Gestion complète de votre présence digitale. Stratégie, contenu, publicité, reporting.',
    ecoFriendly: false,
    skills: ['Stratégie digitale', 'Publicités', 'Analytics', 'Community management'],
    experience: '9 ans'
  },

  // ========== BANQUIERS ==========
  {
    id: 'partner-banquier-1',
    name: 'Crédit Pro Restauration',
    role: 'banquier',
    specialty: 'Financement professionnel CHR',
    location: 'Paris',
    rating: 4.6,
    reviewCount: 124,
    price: 'Conseil gratuit',
    availability: 'Sur rendez-vous',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=61',
    badges: ['Spécialiste CHR', 'Prêts avantageux', 'Accompagnement'],
    description: 'Conseiller financier spécialisé CHR. Prêts professionnels, leasing matériel, trésorerie.',
    ecoFriendly: false,
    skills: ['Financement', 'Prêts pro', 'Conseil', 'Trésorerie'],
    experience: '15 ans'
  },
  {
    id: 'partner-banquier-2',
    name: 'Banque des Entrepreneurs',
    role: 'banquier',
    specialty: 'Création & développement entreprise',
    location: 'Lyon',
    rating: 4.7,
    reviewCount: 187,
    price: 'Gratuit',
    availability: 'Disponible',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=62',
    badges: ['Start-up friendly', 'Accompagnement', 'Prêts création'],
    description: 'Banque spécialisée entrepreneurs. Accompagnement création, prêts à taux préférentiels.',
    ecoFriendly: true,
    skills: ['Création entreprise', 'Développement', 'Prêts', 'Conseil stratégique'],
    experience: '20 ans'
  },
  {
    id: 'partner-banquier-3',
    name: 'Finance & Investissement',
    role: 'banquier',
    specialty: 'Investissement et croissance',
    location: 'Marseille',
    rating: 4.8,
    reviewCount: 213,
    price: 'Sur devis',
    availability: 'Rendez-vous',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=63',
    badges: ['Gros projets', 'Investisseurs réseau', 'Expertise'],
    description: 'Conseiller investissement. Financement projets d\'expansion, mise en relation investisseurs.',
    ecoFriendly: false,
    skills: ['Investissement', 'Levée de fonds', 'Stratégie financière', 'Réseau'],
    experience: '18 ans'
  },

  // ========== COMPTABLES ==========
  {
    id: 'partner-comptable-1',
    name: 'Expert Comptable CHR',
    role: 'comptable',
    specialty: 'Comptabilité restaurants',
    location: 'Paris',
    rating: 4.9,
    reviewCount: 267,
    price: '200€/mois',
    availability: 'Nouveaux clients',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=71',
    badges: ['Expert-comptable', 'Spécialiste CHR', 'TVA restaurant'],
    description: 'Expert-comptable spécialisé restauration. Gestion complète, optimisation fiscale, conseils.',
    ecoFriendly: false,
    skills: ['Comptabilité', 'TVA', 'Fiscal', 'Social', 'Optimisation'],
    experience: '21 ans'
  },
  {
    id: 'partner-comptable-2',
    name: 'Compta & Gestion Pro',
    role: 'comptable',
    specialty: 'Gestion comptable PME',
    location: 'Lyon',
    rating: 4.7,
    reviewCount: 198,
    price: '180€/mois',
    availability: 'Disponible',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=72',
    badges: ['Certifié', 'Déclarations', 'Conseil gestion'],
    description: 'Cabinet comptable pour PME. Comptabilité, déclarations, bulletins de paie, conseils gestion.',
    ecoFriendly: false,
    skills: ['Comptabilité générale', 'Paie', 'Déclarations', 'Gestion'],
    experience: '14 ans'
  },
  {
    id: 'partner-comptable-3',
    name: 'Fiscalité & Optimisation',
    role: 'comptable',
    specialty: 'Optimisation fiscale',
    location: 'Bordeaux',
    rating: 4.8,
    reviewCount: 176,
    price: '250€/mois',
    availability: 'Sur rendez-vous',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=73',
    badges: ['Optimisation', 'Audit', 'Stratégie fiscale'],
    description: 'Spécialiste optimisation fiscale. Audit, stratégie fiscale, montages juridiques.',
    ecoFriendly: false,
    skills: ['Optimisation fiscale', 'Audit', 'Stratégie', 'Juridique'],
    experience: '19 ans'
  },

  // ========== INVESTISSEURS ==========
  {
    id: 'partner-investisseur-1',
    name: 'Business Angels Restauration',
    role: 'investisseur',
    specialty: 'Investissement restaurants innovants',
    location: 'Paris',
    rating: 4.7,
    reviewCount: 89,
    price: '50K-500K€',
    availability: 'Projets sélectionnés',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=81',
    badges: ['Business Angel', 'Réseau', 'Accompagnement'],
    description: 'Business Angel spécialisé restauration. Investissement + accompagnement stratégique.',
    ecoFriendly: true,
    skills: ['Investissement', 'Conseil stratégique', 'Réseau', 'Croissance'],
    experience: '12 ans'
  },
  {
    id: 'partner-investisseur-2',
    name: 'Fonds d\'Investissement Food',
    role: 'investisseur',
    specialty: 'Capital développement food-tech',
    location: 'Paris',
    rating: 4.9,
    reviewCount: 124,
    price: '100K-2M€',
    availability: 'Dossiers solides',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=82',
    badges: ['Fonds investment', 'Food-tech', 'Scaling'],
    description: 'Fonds d\'investissement food-tech. Capital développement pour restaurants et start-ups food.',
    ecoFriendly: false,
    skills: ['Capital développement', 'Due diligence', 'Scaling', 'Exit strategy'],
    experience: '8 ans'
  },
  {
    id: 'partner-investisseur-3',
    name: 'Investisseur Privé',
    role: 'investisseur',
    specialty: 'Investissement privé CHR',
    location: 'Lyon',
    rating: 4.6,
    reviewCount: 67,
    price: '20K-200K€',
    availability: 'Projets prometteurs',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=83',
    badges: ['Investisseur privé', 'Flexible', 'Partenariat'],
    description: 'Investisseur privé. Participations minoritaires, accompagnement personnalisé.',
    ecoFriendly: true,
    skills: ['Investissement privé', 'Partenariat', 'Conseil', 'Développement'],
    experience: '16 ans'
  },

  // ========== AUDITEURS ==========
  {
    id: 'partner-auditeur-1',
    name: 'Audit & Conformité Pro',
    role: 'auditeur',
    specialty: 'Audit hygiène et sécurité',
    location: 'Paris',
    rating: 4.8,
    reviewCount: 143,
    price: '350€/audit',
    availability: 'Planning 2 semaines',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=91',
    badges: ['Certifié HACCP', 'Audit complet', 'Recommandations'],
    description: 'Auditeur spécialisé hygiène alimentaire. Audit HACCP, conformité, plan d\'action.',
    ecoFriendly: false,
    skills: ['HACCP', 'Hygiène', 'Sécurité alimentaire', 'Conformité'],
    experience: '17 ans'
  },
  {
    id: 'partner-auditeur-2',
    name: 'Consultant Qualité Restauration',
    role: 'auditeur',
    specialty: 'Audit qualité et certification',
    location: 'Lyon',
    rating: 4.7,
    reviewCount: 112,
    price: '450€/jour',
    availability: 'Disponible',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=92',
    badges: ['Certifications', 'Qualité', 'Formation équipes'],
    description: 'Consultant qualité. Audit, mise en conformité, certifications (ISO, HACCP, etc.).',
    ecoFriendly: false,
    skills: ['Audit qualité', 'Certifications', 'Formation', 'Conformité'],
    experience: '22 ans'
  },

  // ========== DEMANDEURS D'EMPLOI ==========
  {
    id: 'partner-candidat-1',
    name: 'Thomas Serveur Pro',
    role: 'candidat',
    specialty: 'Serveur expérimenté',
    location: 'Paris',
    rating: 4.7,
    reviewCount: 45,
    price: '1900-2300€/mois',
    availability: 'Immédiatement',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=101',
    badges: ['8 ans d\'expérience', 'Bilingue', 'Service haut de gamme'],
    description: 'Serveur professionnel avec 8 ans d\'expérience. Bilingue français-anglais. Service gastronomique.',
    ecoFriendly: false,
    skills: ['Service en salle', 'Sommellerie', 'Anglais courant', 'Relation client'],
    experience: '8 ans'
  },
  {
    id: 'partner-candidat-2',
    name: 'Marie Chef de Partie',
    role: 'candidat',
    specialty: 'Chef de partie',
    location: 'Lyon',
    rating: 4.8,
    reviewCount: 38,
    price: '2100-2600€/mois',
    availability: 'Préavis 1 mois',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=102',
    badges: ['CAP Cuisine', '6 ans expérience', 'Pâtisserie'],
    description: 'Chef de partie polyvalente. Cuisine française et pâtisserie. CAP + 6 ans d\'expérience.',
    ecoFriendly: false,
    skills: ['Cuisine française', 'Pâtisserie', 'Gestion stocks', 'Équipe'],
    experience: '6 ans'
  },
  {
    id: 'partner-candidat-3',
    name: 'Lucas Barman Mixologue',
    role: 'candidat',
    specialty: 'Barman / Mixologue',
    location: 'Nice',
    rating: 4.9,
    reviewCount: 52,
    price: '1800-2200€/mois',
    availability: 'Disponible',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=103',
    badges: ['Cocktails signature', 'Barista', 'Créatif'],
    description: 'Barman mixologue créatif. Cocktails signature, bar à cocktails, formations barista.',
    ecoFriendly: false,
    skills: ['Cocktails', 'Bar', 'Café barista', 'Créativité'],
    experience: '5 ans'
  },
  {
    id: 'partner-candidat-4',
    name: 'Sophie Commis de Cuisine',
    role: 'candidat',
    specialty: 'Commis de cuisine',
    location: 'Marseille',
    rating: 4.5,
    reviewCount: 23,
    price: '1650-1850€/mois',
    availability: 'Immédiatement',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=104',
    badges: ['CAP Cuisine', 'Motivée', 'Apprentissage rapide'],
    description: 'Commis de cuisine motivée. CAP Cuisine, 2 ans d\'expérience, envie d\'apprendre.',
    ecoFriendly: false,
    skills: ['Bases cuisine', 'Préparations', 'Mise en place', 'Équipe'],
    experience: '2 ans'
  },
  {
    id: 'partner-candidat-5',
    name: 'Alexandre Plongeur',
    role: 'candidat',
    specialty: 'Plongeur / Aide de cuisine',
    location: 'Toulouse',
    rating: 4.6,
    reviewCount: 31,
    price: '1580-1750€/mois',
    availability: 'Disponible',
    verified: true,
    avatar: 'https://i.pravatar.cc/150?img=105',
    badges: ['Polyvalent', 'Rigoureux', 'Travailleur'],
    description: 'Plongeur polyvalent et rigoureux. Expérience en aide de cuisine, nettoyage, hygiène.',
    ecoFriendly: false,
    skills: ['Plonge', 'Nettoyage', 'Hygiène', 'Aide cuisine'],
    experience: '3 ans'
  }
];
